SKIP_SITES = {
    'aeon.co',
    'altaonline.com',
    'americanaffairsjournal.org',
    'apollo-magazine.com',
    'asteriskmag.com',
    'astralcodexten.com',
    'magazine.atavist.com',

    'betonit.substack.com',
    # blogspot.com
    'steve-yegge.blogspot.com',
    'bloodknife.com',
    'bookforum.com',
    'brave.com',
    'buckleyschool.com',

    'chronicle.com',
    'city-journal.org',
    'cnn.com',
    'commonwealmagazine.org',
    'compactmag.com',

    'dannyreviews.com',
    'dirt.fyi',
    'discoursemagazine.com',
    'dissentmagazine.org',
    'documentjournal.com',
    'dropbox.com',
    'dynomight.net',

    'emergencemagazine.org',
    'english.elpais.com',
    'europeanreviewofbooks.com',

    'fantasticmetropolis.com',
    'francisdiclemente.com',
    'ft.com',

    'glamour.com',
    # google.com
    'docs.google.com',
    'granta.com',

    'hakaimagazine.com',
    'hedgehogreview.com',
    'hudsonreview.com',

    'isonomiaquarterly.com',

    'jacobin.com',
    'jewishreviewofbooks.com',

    'kirkusreviews.com',
    'knowablemagazine.org',

    'laphamsquarterly.org',
    'lareviewofbooks.org',
    'literaryreview.co.uk',
    'lithub.com',
    'longnow.org',
    'longreads.com',
    'lrb.co.uk',
    'lynalden.com',

    'mankindquarterly.org',
    'marginalrevolution.com',
    # medium.com
    'doctorow.medium.com',
    'steve-yegge.medium.com',
    'meltingasphalt.com',
    'milkyeggs.com',
    'mindmatters.ai',
    'monthlyreview.org',
    'motherjones.com',

    'nakedcapitalism.com',
    'narratively.com',
    'nationalreview.com',
    'neomodern.com',
    'newcriterion.com',
    'newleftreview.org',
    'newrepublic.com',
    'newscientist.com',
    'newstatesman.com',
    'noahpinion.blog',
    'noemamag.com',
    'nplusonemag.com',
    'nybooks.com',
    'nypost.com',

    'openculture.com',
    'openthemagazine.com',
    'otherlife.co',
    'ourcivilisation.com',
    'oxfordpoliticalreview.com',

    'palladiummag.com',
    'patrickcollison.com',
    'paulgraham.com',
    'plough.com',
    'pluralistic.net',
    'project-syndicate.org',
    'psmag.com',
    'publicdomainreview.org',

    'quillette.com',
    'quora.com',

    'racket.news',
    'reason.com',

    'samaltman.com',
    'seths.blog',
    'sive.rs',
    'slatestarcodex.com',
    'open.spotify.com',
    'spy.com',
    # substack.com
    'astralcodexten.substack.com',
    'dynomight.substack.com',
    'noahpinion.substack.com',
    'thezvi.substack.com',

    'tabletmag.com',
    'the-fence.com',
    'theamericanconservative.com',
    'theamericanscholar.org',
    'thebaffler.com',
    'thecritic.co.uk',
    'thedial.world',
    'thedriftmag.com',
    'theepochtimes.com',
    'thelampmagazine.com',
    'themarginalian.org',
    'themillions.com',
    'thenewatlantis.com',
    'theparisreview.org',
    'thepointmag.com',
    'thestacksreader.com',
    'thewalrus.ca',
    'thoughtco.com',
    'tiktok.com',
    'transom.org',
    'twitter.com',
    'business.twitter.com',

    'unherd.com',

    'versobooks.com',
    'vestoj.com',

    'wheresyoured.at',
    'wmagazine.com',

    'x.com',
    'xtramagazine.com',

    'yalereview.org',

    '972mag.com',
}
