#!/bin/sh

export FLASK_NEWS_PATH=/var/lib/news/news.json

cd /usr/local/news || exit 1

python3 extractor.py \
    --cache-path="$FLASK_NEWS_PATH" \
    --poll=5 &
gunicorn \
    --group=news \
    --user=news \
    --workers=4 \
    'server:app' &
nginx &

wait
exit $?
