#!/bin/sh

export FLASK_NEWS_PATH=/var/lib/news/news.json


su news -s /bin/sh -c extract

cd /usr/local/news || exit 1
gunicorn \
    --group=news \
    --user=news \
    --workers=4 \
    'server:app' &

nginx &

crond -f -l 10 -L /dev/stdout &

wait
exit $?
