name: BuildAndDeploy
run-name: ${{github.actor}} is building and deploying.
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_ACCESS_KEY_SECRET: ${{secrets.AWS_ACCESS_KEY_SECRET}}
jobs:
  News:
    name: News
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
          aws-region: us-west-1
      - name: Test
        working-directory: news
        run : make check
      - name: Deploy
        working-directory: news
        run : make deploy
