name: BuildAndDeploy
run-name: ${{ github.actor }} is building and deploying.
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  News:
    name: News
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run : |
          cd '${{github.workspace}}/news'
          make build
